# baseURL = "http://localhost:1313/"  # Temporarily set this for local testing (change back to your live URL later)
baseURL = "https://jlfuentesacosta.github.io/jlfuentesacosta/"  # Update with your GitHub details
languageCode = "en-us"
title = "Juan L. Fuentes-Acosta"
theme = "my-theme"  # Points to our custom theme

# Enable raw HTML in markdown
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Minimal params for the theme
[params]
  author = "Juan L. Fuentes-Acosta"
  dateform = "Jan 2, 2006"  # Simple date format
  dateformShort = "Jan 2"
  description = "Econ PhD Candidate on the Job Market"
  keywords = "economics, phd, jmp, job market, research"
  defaultTheme = "dark"  # Or "dark" if you prefer
  disableReadOtherPosts = true  # Keeps it minimal, no post suggestions
  enableSharingButtons = false  # No social buttons
  enableGlobalLanguageMenu = false  # No language switcher
  email = "fuentejc@bc.edu"
  photo = "images/headshot-jmsite.png"  # Upload a photo to static/images/ later

# Simple menu
[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/"
  weight = 1
[[menu.main]]
  name = "Research"
  url = "/research/"
  weight = 2
[[menu.main]]
  name = "CV"
  url = "/cv/"
  weight = 3
